"""SHA-256 verification, per-update temp directories, and install-result reporting."""
import hashlib
import io
import sys

import pytest

sys.path.insert(0, "src")

import update_checker
from update_checker import UpdateIntegrityError

GOOD = "a" * 64


@pytest.fixture(autouse=True)
def _isolated_state(tmp_path, monkeypatch):
    monkeypatch.setattr(update_checker.tempfile, "gettempdir", lambda: str(tmp_path))


def _serve(text):
    """Stand in for urlopen returning a checksum file body."""
    class _Resp:
        def read(self):
            return text.encode("utf-8")

        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    return lambda req, **kwargs: _Resp()


# ── checksum file parsing ───────────────────────────────────────────────────

def test_parse_checksums_reads_sha256sum_format():
    text = f"{GOOD}  BrightspacePagesAutomator-Setup-Latest.exe\n"
    assert update_checker.parse_checksums(text) == {
        "BrightspacePagesAutomator-Setup-Latest.exe": GOOD
    }


def test_parse_checksums_skips_comments_blanks_and_junk():
    text = "\n".join([
        "# generated by CI",
        "",
        "not-a-checksum-line",
        "zz  bad-digest.exe",
        f"{GOOD}  Setup.exe",
    ])
    assert update_checker.parse_checksums(text) == {"Setup.exe": GOOD}


def test_parse_checksums_tolerates_binary_star_prefix():
    assert update_checker.parse_checksums(f"{GOOD} *Setup.exe") == {"Setup.exe": GOOD}


# ── obtaining the expected digest ───────────────────────────────────────────

def test_missing_checksum_asset_is_rejected():
    with pytest.raises(UpdateIntegrityError) as e:
        update_checker.fetch_expected_sha256(None, "Setup.exe")
    assert update_checker.CHECKSUM_ASSET_NAME in str(e.value)


def test_unreachable_checksum_file_is_rejected(monkeypatch):
    def _boom(req, timeout=None):
        raise OSError("connection reset")

    monkeypatch.setattr(update_checker.urllib.request, "urlopen", _boom)
    with pytest.raises(UpdateIntegrityError) as e:
        update_checker.fetch_expected_sha256("https://example.test/sums", "Setup.exe")
    assert "Could not download" in str(e.value)


def test_malformed_checksum_file_is_rejected(monkeypatch):
    monkeypatch.setattr(
        update_checker.urllib.request, "urlopen", _serve("garbage\nmore garbage\n")
    )
    with pytest.raises(UpdateIntegrityError) as e:
        update_checker.fetch_expected_sha256("https://example.test/sums", "Setup.exe")
    assert "malformed" in str(e.value)


def test_checksum_file_without_our_asset_is_rejected(monkeypatch):
    monkeypatch.setattr(
        update_checker.urllib.request, "urlopen", _serve(f"{GOOD}  SomethingElse.exe")
    )
    with pytest.raises(UpdateIntegrityError) as e:
        update_checker.fetch_expected_sha256("https://example.test/sums", "Setup.exe")
    assert "does not list Setup.exe" in str(e.value)


def test_matching_entry_is_returned(monkeypatch):
    monkeypatch.setattr(
        update_checker.urllib.request, "urlopen", _serve(f"{GOOD.upper()}  Setup.exe")
    )
    digest = update_checker.fetch_expected_sha256("https://example.test/sums", "Setup.exe")
    assert digest == GOOD


# ── verifying the file on disk ──────────────────────────────────────────────

def test_matching_checksum_passes(tmp_path):
    installer = tmp_path / "Setup.exe"
    installer.write_bytes(b"installer bytes")
    expected = hashlib.sha256(b"installer bytes").hexdigest()

    assert update_checker.verify_installer_checksum(installer, expected) == expected


def test_matching_checksum_is_case_insensitive(tmp_path):
    installer = tmp_path / "Setup.exe"
    installer.write_bytes(b"installer bytes")
    expected = hashlib.sha256(b"installer bytes").hexdigest()

    assert update_checker.verify_installer_checksum(installer, expected.upper()) == expected


def test_mismatched_checksum_is_rejected(tmp_path):
    installer = tmp_path / "Setup.exe"
    installer.write_bytes(b"tampered")

    with pytest.raises(UpdateIntegrityError) as e:
        update_checker.verify_installer_checksum(installer, GOOD)
    assert "does not match" in str(e.value)


def test_empty_expected_checksum_is_rejected(tmp_path):
    installer = tmp_path / "Setup.exe"
    installer.write_bytes(b"anything")

    with pytest.raises(UpdateIntegrityError):
        update_checker.verify_installer_checksum(installer, "")


def test_release_info_exposes_the_checksum_asset():
    info = update_checker._release_info({
        "tag_name": "v0.8.5-99",
        "assets": [
            {"name": "BrightspacePagesAutomator-Setup-Latest.exe",
             "browser_download_url": "https://example.test/latest.exe"},
            {"name": update_checker.CHECKSUM_ASSET_NAME,
             "browser_download_url": "https://example.test/sums"},
        ],
    })

    assert info["checksum_name"] == update_checker.CHECKSUM_ASSET_NAME
    assert info["checksum_url"] == "https://example.test/sums"


def test_release_info_without_a_checksum_asset_has_none():
    info = update_checker._release_info({"tag_name": "v1", "assets": []})

    assert info["checksum_url"] is None


# ── per-update temp directory ───────────────────────────────────────────────

def test_new_update_dir_is_unique_and_prefixed():
    first = update_checker.new_update_dir()
    second = update_checker.new_update_dir()
    try:
        assert first != second
        assert first.is_dir() and second.is_dir()
        assert first.name.startswith(update_checker.UPDATE_DIR_PREFIX)
    finally:
        update_checker.cleanup_update_dir(first)
        update_checker.cleanup_update_dir(second)


def test_cleanup_removes_the_directory_and_its_contents():
    path = update_checker.new_update_dir()
    (path / "Setup.exe").write_bytes(b"x")

    update_checker.cleanup_update_dir(path)

    assert not path.exists()


def test_cleanup_of_none_is_a_no_op():
    update_checker.cleanup_update_dir(None)


# ── installer result hand-back ──────────────────────────────────────────────

def test_no_result_file_reports_nothing():
    assert update_checker.consume_installer_result() is None


def test_successful_install_is_recorded_and_consumed():
    update_checker.update_result_path().write_text("exit=0\n", encoding="utf-8")

    state = update_checker.consume_installer_result()

    assert state["last_install_result"] == "Update installed"
    assert state["setup_exit_code"] == 0
    # Consumed exactly once — a stale file must not re-report on every launch.
    assert not update_checker.update_result_path().exists()
    assert update_checker.consume_installer_result() is None


def test_failed_install_is_recorded_with_its_exit_code():
    update_checker.update_result_path().write_text("exit=5\n", encoding="utf-8")

    state = update_checker.consume_installer_result()

    assert state["last_install_result"] == "Update failed"
    assert state["setup_exit_code"] == 5
    assert "code 5" in state["last_install_detail"]
    assert "NOT applied" in state["last_install_detail"]


def test_unreadable_exit_code_is_treated_as_failure():
    update_checker.update_result_path().write_text("exit=banana\n", encoding="utf-8")

    state = update_checker.consume_installer_result()

    assert state["last_install_result"] == "Update failed"
    assert state["setup_exit_code"] == ""


def test_failed_install_survives_the_next_up_to_date_check(monkeypatch):
    """The check that runs seconds after launch must not bury the failure."""
    update_checker.update_result_path().write_text("exit=5\n", encoding="utf-8")
    update_checker.consume_installer_result()

    update_checker.record_update_result("Up to date", latest_build="v0.8.5-99")
    diagnostics = update_checker.get_update_diagnostics()

    assert diagnostics["last_update_result"] == "Up to date"
    assert diagnostics["last_install_result"] == "Update failed"
    assert diagnostics["setup_exit_code"] == 5
