"""Consistent link behavior for pages generated by the app."""

from bs4 import BeautifulSoup


def open_page_links_in_new_window(markup: str) -> str:
    """Set navigational links to Brightspace's "New window" link option.

    Fragment links and non-browser actions stay as authored. Preserve existing
    rel values while adding noopener for links that open a new browsing context.
    """
    if not markup or "<a" not in markup.lower():
        return markup

    soup = BeautifulSoup(markup, "html.parser")
    changed = False
    for anchor in soup.find_all("a", href=True):
        href = str(anchor["href"]).strip()
        if not href or href.startswith("#") or href.lower().startswith(
            ("mailto:", "tel:", "javascript:", "data:")
        ):
            continue
        if anchor.get("target") != "_blank":
            anchor["target"] = "_blank"
            changed = True
        rel = list(anchor.get("rel") or [])
        if "noopener" not in rel:
            anchor["rel"] = [*rel, "noopener"]
            changed = True

    return str(soup) if changed else markup
